### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by RoonMoonlight** [FoundationGames/EnhancedBlockEntities#127]

**Comment by litoj** [comment]
```
[13:40:27] [Render thread/ERROR]: Mixin apply for mod enhancedblockentities failed enhancedblockentities.mixins.json:SignEditScreenMixin from mod enhancedblockentities -> net.minecraft.class_498: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_3031 was not located in the target class net.minecraft.class_498. Using refmap enhancedblockentities-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_3031 was not located in the target class net.minecraft.class_498. Using refmap enhancedblockentities-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.pieking1215.invmove.module.VanillaModule16.<init>(VanillaModule16.java:63) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at me.pieking1215.invmove.module.VanillaModule19.<init>(VanillaModule19.java:3) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at me.pieking1215.invmove.InvMove19.getVanillaModule(InvMove19.java:17) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at me.pieking1215.invmove.InvMove.<init>(InvMove.java:82) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at me.pieking1215.invmove.InvMove19.<init>(InvMove19.java:12) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at me.pieking1215.invmove.fabric.InvMoveFabric$1.<init>(InvMoveFabric.java:18) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at me.pieking1215.invmove.fabric.InvMoveFabric.onInitializeClient(InvMoveFabric.java:18) ~[InvMove-1.19-0.8.1-Fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.14.11.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:465) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
```

**Comment by FoundationGames** [comment]
EBE is not compatible with 1.19.3 and an update is necessary

**Comment by haykam821** [comment]
A pull request is open to port one required dependency, ARRP, to Minecraft 1.19.3: Devan-Kerman/ARRP#79.

**Comment by ggvbo** [comment]
> A pull request is open to port one required dependency, ARRP, to Minecraft 1.19.3: [Devan-Kerman/ARRP#79](https://github.com/Devan-Kerman/ARRP/pull/79).

PR was merged.

**Comment by AbrasiveBoar902** [comment]
So is the update in progress?

**Comment by Brottweiler** [comment]
> So is the update in progress?

If you want to help out speed up the process you can send a pull request.

**Comment by giorov** [comment]
bump

**Comment by TechPro424** [comment]
Please update to 1.19.3

**Comment by RoonMoonlight** [comment]
> Please update to 1.19.3

Patient, please. The author is working hard to get 1.19.3 support.

If you can't wait please consider making pull request.

**Comment by haykam821** [comment]
The main issue regarding support for Minecraft 1.19.3 is that ARRP seems to be broken with the current setup. While the mod compiles, its assets generated at runtime won't be loaded.

**Comment by schrummy14** [comment]
Hello,
Are the issues still with the ARRP dependency? 
Thank you

**Comment by EGOIST1372** [comment]
just wanted to get updates on my email when this issue get any update
hope it get update soon
thanks in advance <3

**Comment by Brottweiler** [comment]
> just wanted to get updates on my email when this issue get any update hope it get update soon thanks in advance <3

Off-topic but on the right side you can press the **Subscribe** button to get notifications, no need to leave a comment.

**Comment by jacklollz2** [comment]
While you guys wait, check out [FastChest](https://github.com/FakeDomi/FastChest)
This improves the FPS of chests when near them, I have a giant storage room and looking in its direction my game hardcore lags, but with FastChest that's fixed. With Enhanced Block Entities this performance problem is fixed and the animations work, unfortunately there is no 1.19.3 build working, so I am forced to use FastChest.

**Comment by RoonMoonlight** [comment]
> While you guys wait, check out [FastChest](https://github.com/FakeDomi/FastChest)
> This improves the FPS of chests when near them, I have a giant storage room and looking in its direction my game hardcore lags, but with FastChest that's fixed. With Enhanced Block Entities this performance problem is fixed and the animations work, unfortunately there is no 1.19.3 build working, so I am forced to use FastChest.

Fast Chest is not considered as alternative since it doesn't do the same for other entity blocks

**Comment by intergrav** [comment]
> Fast Chest is not considered as alternative since it doesn't do the same for other entity blocks

To be fair, chests can be quite a big reason that people use EBE due to storage rooms and such so it could be considered a good *temporary* alternative while we wait for EBE 1.19.3

**Comment by Obscure2020** [comment]
Thanks for the [FastChest](https://github.com/FakeDomi/FastChest) suggestion. I don't think I'll use it because I recently got a somewhat more powerful computer, but you make a very fair point. Chests are a big one.

Admittedly I did start out using [FastChest](https://github.com/FakeDomi/FastChest) along with [Better Beds](https://modrinth.com/mod/better-beds), but I switched to EBE because it kept the animations working and it applied the same fix to all the other block entities that really don't have any business being entities. The ability to get smooth lighting on everything was actually a huge selling point for me. I'm a quality hog, which was the main reason why I originally got into modding my game. I didn't wanna have to turn down my video settings to get better FPS on my old, slow laptop! I wanted to crank everything to _Fabulous_ and use mods to pick up the slack.

I've been waiting for EBE to be updated for quite a while now. I do hope @FoundationGames is still up for it.

**Comment by Brokkonaut** [comment]
If you can build mods yourself, I can recommend this fork, that is updated for 1.19.3: https://github.com/xGab0/EnhancedBlockEntities

**Comment by Nolij** [comment]
> If you can build mods yourself, I can recommend this fork, that is updated for 1.19.3: https://github.com/xGab0/EnhancedBlockEntities

Unfortunately the ARRP dependency fails to download and the dev's official maven is giving an SSL error for some reason.

**Comment by SynergyShadow** [comment]
> If you can build mods yourself, I can recommend this fork, that is updated for 1.19.3: https://github.com/xGab0/EnhancedBlockEntities

Doesn't work

**Comment by Nolij** [comment]
> > If you can build mods yourself, I can recommend this fork, that is updated for 1.19.3: https://github.com/xGab0/EnhancedBlockEntities
> 
> Doesn't work

In the interest of not forking a fork I'll just leave this here:

```diff
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle b/build.gradle
--- a/build.gradle    (revision f41ef27117ee797ccf43bde684bb05cb14f49a59)
+++ b/build.gradle    (date 1677004142239)
@@ -44,6 +44,14 @@
     maven { url = "https://api.modrinth.com/maven/" }
     maven { url = "https://maven.gegy.dev/" }
     maven { url = "https://notalpha.dev/maven/" }
+    maven {
+        name = "Modrinth"
+        url = "https://api.modrinth.com/maven"
+
+        content {
+            includeGroup "maven.modrinth"
+        }
+    }
 }
 
 dependencies {
@@ -56,8 +64,8 @@
     modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
 
     // ARRP. This is for generating a runtime resource pack (conditionally, as well)
-    modImplementation "net.devtech:arrp:${project.arrp_version}"
-    include "net.devtech:arrp:${project.arrp_version}"
+    modImplementation "maven.modrinth:arrp:${project.arrp_version}"
+    include "maven.modrinth:arrp:${project.arrp_version}"
 
     // Mod Menu because config screen access from another place
     modApi "com.terraformersmc:modmenu:${project.modmenu_version}"
```

**Comment by SynergyShadow** [comment]
> > If you can build mods yourself, I can recommend this fork, that is updated for 1.19.3: https://github.com/xGab0/EnhancedBlockEntities
> 
> Doesn't work

Got it working, for 1.19.3. https://github.com/shadowtigercool/EnhancedBlockEntities

**Comment by SynergyShadow** [comment]
> > > If you can build mods yourself, I can recommend this fork, that is updated for 1.19.3: https://github.com/xGab0/EnhancedBlockEntities
> > 
> > 
> > Doesn't work
> 
> Got it working, for 1.19.3. https://github.com/shadowtigercool/EnhancedBlockEntities

 Only thing though has Broken Textures when breaking, chest, bed and signs. but it isn't Game breaking, I haven't tested anything else. like custom textures.  if you want to test it, go ahead, has a bug where the sign UI Is off the screen

**Comment by FoundationGames** [comment]
A 1.19.3 version with bug fixes and support for hanging signs is nearly complete, though bear in mind I am not guaranteed to offer help if you do decide to use a fork for the time being

**Comment by Nolij** [comment]
> A 1.19.3 version with bug fixes and support for hanging signs is nearly complete, though bear in mind I am not guaranteed to offer help if you do decide to use a fork for the time being

I'm sure the official update will be better than this regardless, but for the time being it's better than FastChest or nothing at all.

**Comment by purple512** [comment]
Another option to try if you're really impatient to play 1.19.3 is the [ImmediatelyFast mod](https://modrinth.com/mod/immediatelyfast).

**Comment by Obscure2020** [comment]
ImmediatelyFast is a fantastic mod! Highly recommend that one.

**Comment by Brottweiler** [comment]
Resolved in https://github.com/FoundationGames/EnhancedBlockEntities/commit/014168895fa7137d9bef73a4dc7045d98437ae5d 🎉
