### ISSUE TITLE
1.19.2 Ringing a bell crashes the game

### ISSUE THREAD

**Issue by WatNTarnation** [FoundationGames/EnhancedBlockEntities#145]
I was recently showing my world to someone and while doing so rang a bell. My game crashed immediately afterwards. This has never happened with any mod before so i tried ringing it again after boot and the game crashed the same way. There seems to be an error. I've copied part of the crash report and will paste it below. Not a huge deal, but I figured I'd try and bring the bug to your attention if it hasn't been done so yet.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-03-29 23:10:53
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4707(net.minecraft.class_2680, net.minecraft.class_2350, net.minecraft.class_5819)" because "model" is null
	at foundationgames.enhancedblockentities.util.EBEUtil.renderBakedModel(EBEUtil.java:36)
	at foundationgames.enhancedblockentities.client.render.entity.BellBlockEntityRendererOverride.render(BellBlockEntityRendererOverride.java:44)
	at net.minecraft.class_824.handler$zif000$enhanced_bes$renderOverrides(class_824.java:530)
	at net.minecraft.class_824.method_23079(class_824.java)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderBlockEntities(ShadowRenderer.java:563)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:483)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
	at net.minecraft.class_761.handler$bfe000$iris$renderTerrainShadows(class_761.java:8536)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at foundationgames.enhancedblockentities.util.EBEUtil.renderBakedModel(EBEUtil.java:36)
	at foundationgames.enhancedblockentities.client.render.entity.BellBlockEntityRendererOverride.render(BellBlockEntityRendererOverride.java:44)
	at net.minecraft.class_824.handler$zif000$enhanced_bes$renderOverrides(class_824.java:530)
	at net.minecraft.class_824.method_23079(class_824.java)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderBlockEntities(ShadowRenderer.java:563)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:483)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
	at net.minecraft.class_761.handler$bfe000$iris$renderTerrainShadows(class_761.java:8536)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Block Entity Details --
Details:
	Name: minecraft:bell // net.minecraft.class_3721
	Block: Block{minecraft:bell}[attachment=floor,facing=south,powered=false]
	Block location: World: (271,73,-21), Section: (at 15,9,11 in 16,4,-2; chunk contains blocks 256,-64,-32 to 271,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{minecraft:bell}[attachment=floor,facing=south,powered=false]
	Block location: World: (271,73,-21), Section: (at 15,9,11 in 16,4,-2; chunk contains blocks 256,-64,-32 to 271,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderBlockEntities(ShadowRenderer.java:563)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:483)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
	at net.minecraft.class_761.handler$bfe000$iris$renderTerrainShadows(class_761.java:8536)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Razatop** [comment]
Same, you ever find a solution?
