### ISSUE TITLE
Some bugs/problems in EBE 0.9

### ISSUE THREAD

**Issue by HhiPyrene** [FoundationGames/EnhancedBlockEntities#158]
Using LBG, the particles lost like it's in the version 0.8.

**Comment by YukiAyase** [comment]
Providing a screenshot would've been better but I'll help you with that
I assume this is what they mean by "particles lost"

Block breaking particles have missing textures when "Experimental feature" is turned ON for beds, chests and signs
Affected versions are Minecraft 1.19.3, 1.19.4 and 1.20 when LBG is used with EBE

Experimental feature ON **with** LBG
![2023-07-01_12 45 37](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/5c5296a0-d286-4c72-8269-62db9db8e841)
![2023-07-01_12 48 37](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/1f130b39-c772-4749-babe-8c7ffc42ceac)
![2023-07-01_12 37 57](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/caaf1fe1-9fbd-4698-87ec-6e8b5326e75a)
![2023-07-01_12 38 15](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/a522f9a0-ba27-400a-98b9-bb52e3c31797)
![2023-07-01_12 38 40](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/67380ade-5308-4b1f-af91-68b8940f3bc2)

Experimental feature ON **without** LBG
![2023-07-01_12 51 49](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/4fe68f4c-89ea-46d3-b651-375eebf482da)
![2023-07-01_12 49 59](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/c1993bac-6b11-40ea-a534-af178623e0b6)
![2023-07-01_12 51 14](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/ca53cc33-dd31-4b5f-ba14-3433c70f37c6)
![2023-07-01_12 51 24](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/7bf341cc-fe61-4d32-b41d-80e0c387aa41)
![2023-07-01_12 51 00](https://github.com/FoundationGames/EnhancedBlockEntities/assets/64414315/99dbcc7e-2d5a-428d-92c8-c5bee97e0f12)

**Comment by HhiPyrene** [comment]
Also, the smooth lighting on beds looks not so good.![2023-07-01_23.07.50.png](https://github.com/FoundationGames/EnhancedBlockEntities/assets/111572269/839b9023-cafd-46fe-9715-37f995e002c9)

**Comment by HhiPyrene** [comment]
When dump a example resourse, it crash.
```
Description: mouseClicked event handler

java.nio.file.ProviderMismatchException
	at java.base/sun.nio.fs.WindowsPath.toWindowsPath(WindowsPath.java:373)
	at java.base/sun.nio.fs.WindowsPath.resolve(WindowsPath.java:580)
	at java.base/sun.nio.fs.WindowsPath.resolve(WindowsPath.java:42)
	at foundationgames.enhancedblockentities.util.ResourceUtil.dumpModAssets(ResourceUtil.java:288)
	at foundationgames.enhancedblockentities.util.ResourceUtil.dumpAllPacks(ResourceUtil.java:301)
	at foundationgames.enhancedblockentities.util.EBEUtil.dumpResources(EBEUtil.java:67)
	at foundationgames.enhancedblockentities.config.gui.screen.EBEConfigScreen.lambda$addOptions$4(EBEConfigScreen.java:196)
	at dev.lambdaurora.spruceui.option.SpruceCyclingOption.cycle(SpruceCyclingOption.java:47)
	at dev.lambdaurora.spruceui.option.SpruceCyclingOption.lambda$createWidget$0(SpruceCyclingOption.java:53)
	at dev.lambdaurora.spruceui.widget.SpruceButtonWidget.onPress(SpruceButtonWidget.java:32)
	at dev.lambdaurora.spruceui.widget.AbstractSprucePressableButtonWidget.onClick(AbstractSprucePressableButtonWidget.java:32)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.onMouseClick(AbstractSpruceButtonWidget.java:98)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25402(AbstractSpruceWidget.java:136)
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.onMouseClick(SpruceOptionListWidget.java:182)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25402(AbstractSpruceWidget.java:136)
	at dev.lambdaurora.spruceui.widget.container.AbstractSpruceParentWidget.onMouseClick(AbstractSpruceParentWidget.java:92)
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.onMouseClick(SpruceEntryListWidget.java:293)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25402(AbstractSpruceWidget.java:136)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
```

**Comment by muzikbike** [comment]
Crash confirmed.
![2023-07-11_14 28 02](https://github.com/FoundationGames/EnhancedBlockEntities/assets/52297970/588d4664-cf0b-40fa-92ca-62bb66d6f7d6)
