### ISSUE TITLE
Game crashes when trying to use this mod alongside shaders.

### ISSUE THREAD

**Issue by pleepish** [FoundationGames/EnhancedBlockEntities#174]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-07-27 14:31:56
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "dev.tr7zw.exordium.access.SignBufferHolder.renderBuffered(net.minecraft.class_4587, net.minecraft.class_4597, boolean, int)" because "this.renderingSign" is null
	at net.minecraft.class_837.handler$zpc000$exordium$render(class_837.java:1043)
	at net.minecraft.class_837.method_45798(class_837.java)
	at net.minecraft.class_837.enhanced_bes$renderText(class_837.java)
	at foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.render(SignBlockEntityRendererOverride.java:22)
	at net.minecraft.class_824.handler$zlc000$enhancedblockentities$enhanced_bes$renderOverrides(class_824.java:530)
	at net.minecraft.class_824.method_23079(class_824.java)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.class_761.handler$dch000$sodium$onRenderTileEntities(class_761.java:14108)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_837.handler$zpc000$exordium$render(class_837.java:1043)
	at net.minecraft.class_837.method_45798(class_837.java)
	at net.minecraft.class_837.enhanced_bes$renderText(class_837.java)
	at foundationgames.enhancedblockentities.client.render.entity.SignBlockEntityRendererOverride.render(SignBlockEntityRendererOverride.java:22)
	at net.minecraft.class_824.handler$zlc000$enhancedblockentities$enhanced_bes$renderOverrides(class_824.java:530)
	at net.minecraft.class_824.method_23079(class_824.java)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.class_761.handler$dch000$sodium$onRenderTileEntities(class_761.java:14108)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Block Entity Details --
Details:
	Name: minecraft:hanging_sign // net.minecraft.class_7717
	Block: Block{minecraft:spruce_hanging_sign}[attached=false,rotation=12,waterlogged=false]
	Block location: World: (-10,82,-434), Section: (at 6,2,14 in -1,5,-28; chunk contains blocks -16,-64,-448 to -1,319,-433), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{minecraft:spruce_hanging_sign}[attached=false,rotation=12,waterlogged=false]
	Block location: World: (-10,82,-434), Section: (at 6,2,14 in -1,5,-28; chunk contains blocks -16,-64,-448 to -1,319,-433), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.class_761.handler$dch000$sodium$onRenderTileEntities(class_761.java:14108)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['pleepish'/256049, l='ClientLevel', x=7.21, y=80.50, z=-451.06]]
	Chunk stats: 4096, 124
	Level dimension: minecraft:overworld
	Level spawn location: World: (5,80,-456), Section: (at 5,0,8 in 0,5,-29; chunk contains blocks 0,-64,-464 to 15,319,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 58922062 game time, 83599415 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, minecraft:supporteatinganimation, file/better_flame_particles-v1.0-mc1.20-resourcepack.zip, continuity:glass_pane_culling_fix, continuity:default, file/Square corners for Offhand slot v1.1.zip, file/Better+Leaves+Add-on+V3.0-1.20.zip, classic_icons, file/bangetto's Armor Glint.zip, file/VanillaTweaks_r505119.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 487716464 bytes (465 MiB) / 1107296256 bytes (1056 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37460.48
	Virtual memory used (MB): 15727.33
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 29.33
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		bee_info: More Bee info  1.1.2
		bettermounthud: Better Mount HUD 1.2.2
		blanket-client-tweaks: Blanket Client-tweaks 1.1.4-SNAPSHOT-build.21
		bookshelf: Bookshelf 20.0.1
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		chat_heads: Chat Heads 0.10.18
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		continuity: Continuity 3.0.0-beta.3+1.20.1
		debugify: Debugify 1.20.1+2.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		durabilitynotifier: Durability Notifier 1.6.0
		durabilityplus: DurabilityPlus 1.0.2
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.9.4+1.20
		enchdesc: EnchantmentDescriptions 17.0.3
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		exordium: Exordium 1.1.3-mc1.20.1
		extrasounds: ExtraSounds 2.3.1+1.20~lonefelidae16-build.1
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.86.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.0+6c31357e77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.9+132c48c177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.1+9386d8a777
			fabric-models-v0: Fabric Models (v0) 0.4.0+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.0+2e061fd477
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.2+1.20.1
		ferritecore: FerriteCore 6.0.0
		indium: Indium 1.0.21+mc1.20.1
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		litematica: Litematica 0.15.3
		lithium: Lithium 0.11.2
		logical_zoom: Logical Zoom 0.0.20
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.1-fabric
		malilib: MaLiLib 0.16.1
		memoryleakfix: Memory Leak Fix 1.1.1
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 7.2.1
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.20-0.18.1
			conditional-mixin: conditional mixin 0.3.2
		mousetweaks: Mouse Tweaks 2.25
		notenoughanimations: NotEnoughAnimations 1.6.4
		raised: Raised 2.0.0
		raisedxappleskin: Raised x Appleskin 2.5.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.20-build.73
		roughlyenoughitems: Roughly Enough Items 12.0.634
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		simply-no-shading: Simply No Shading 6.0.7+1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.dbc156f
		tooltipfix: ToolTip Fix 1.1.1-1.20
		voicechat: Simple Voice Chat 1.20.1-2.4.12
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 23.6.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Loaded Shaderpack: ComplementaryReimagined_r2.2.1.zip
		Profile: Custom (+31 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, minecraft:supporteatinganimation, file/better_flame_particles-v1.0-mc1.20-resourcepack.zip, continuity:glass_pane_culling_fix, continuity:default, file/Square corners for Offhand slot v1.1.zip, file/Better+Leaves+Add-on+V3.0-1.20.zip, classic_icons, file/bangetto's Armor Glint.zip, file/VanillaTweaks_r505119.zip
	Current Language: en_us
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz

**Comment by pleepish** [comment]
when i remove this mod, the game runs, but all of the text on signs are glitched or completely removed.

**Comment by ImGRUI** [comment]
It's Exordium problem, not related to EBE. It mentioned in Exordium 1.1.3 changelog, just turn off sign buffering in Exordium and it should be fine.

**Comment by pleepish** [comment]
> It's Exordium problem, not related to EBE. It mentioned in Exordium 1.1.3 changelog, just turn off sign buffering in Exordium and it should be fine.

thank you!
