### ISSUE TITLE
The game crashes when starting in version 1.20.5

### ISSUE THREAD

**Issue by J4PC** [FoundationGames/EnhancedBlockEntities#208]
![image](https://github.com/FoundationGames/EnhancedBlockEntities/assets/97805057/c511555f-2682-4b4a-a51c-8da02f4379a4)

> The game crashed whilst bootstrap
> Error: java.lang.ExceptionInInitializerError

farbic-loader-0.15.10-1.20.5 **using the mods:**
- enhancedblockentities-0.9.1+1.20.2
- fabric-api-0.97.6+1.20.5

**Comment by RealmKebab** [comment]
you are using ebe 1.20.2, there is a major difference in 1.20.2 and 1.20.5

**Comment by AethanFoot** [comment]
Well yes, but there isnt a newer version so saying that doesnt add anything

**Comment by RealmKebab** [comment]
> Well yes, but there isnt a newer version so saying that doesnt add anything

i beg your pardon? i'm stating that ebe 1.20.2 doesn't support 1.20.5, it only supports 1.20.2, 1.20.3 & 1.20.4

**Comment by AethanFoot** [comment]
They are just stating it doesnt work with 1.20.5, saying there is a difference between 1.20.2 and 1.20.5 doesn't add anything or help them. 1.20.4 isnt officially supported but works. You kinda just dismissed them, which doesnt help anyone.

**Comment by KorbynTalks** [comment]
For the developers of the mod not knowing what the error actually is here you go:

[13:16:24] [main/ERROR]:
 Mixin apply for mod enhancedblockentities failed enhancedblockentities.mixins.json:DecoratedPotBlockEntityMixin from mod enhancedblockentities -> net.minecraft.class_8172: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on enhanced_bes$updateChunkOnPatternsLoaded could not find any targets matching 'Lnet/minecraft/class_8172;method_11014(Lnet/minecraft/class_2487;)V' in net.minecraft.class_8172. Using refmap enhancedblockentities-refmap.json [PREINJECT Applicator Phase -> enhancedblockentities.mixins.json:DecoratedPotBlockEntityMixin from mod enhancedblockentities -> Prepare Injections ->  -> handler$zem000$enhancedblockentities$enhanced_bes$updateChunkOnPatternsLoaded(Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on enhanced_bes$updateChunkOnPatternsLoaded could not find any targets matching 'Lnet/minecraft/class_8172;method_11014(Lnet/minecraft/class_2487;)V' in net.minecraft.class_8172. Using refmap enhancedblockentities-refmap.json [PREINJECT Applicator Phase -> enhancedblockentities.mixins.json:DecoratedPotBlockEntityMixin from mod enhancedblockentities -> Prepare Injections ->  -> handler$zem000$enhancedblockentities$enhanced_bes$updateChunkOnPatternsLoaded(Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) [?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1242) [client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:53) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:170) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
[13:16:25] [main/WARN]:
 Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:183) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:172) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:872) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2593) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2564) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
