### ISSUE TITLE
Random crash in the End.

### ISSUE THREAD

**Issue by K0-RR** [FoundationGames/EnhancedBlockEntities#26]
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/8/21, 12:54 AM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=type, clazz=class net.minecraft.class_2745, values=[SINGLE, LEFT, RIGHT]} as it does not exist in Block{minecraft:ender_chest}
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
	at net.minecraft.state.State.get(State:95)
	at foundationgames.enhancedblockentities.client.render.entity.ChestBlockEntityRendererOverride.getAnimationProgress(ChestBlockEntityRendererOverride.java:59)
	at foundationgames.enhancedblockentities.client.render.BlockEntityRenderCondition.lambda$static$0(BlockEntityRenderCondition.java:16)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.handler$ela000$enhanced_bes$renderOverrides(BlockEntityRenderDispatcher:1529)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:96)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:128)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:96)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:325)
	at net.minecraft.client.render.WorldRenderer.handler$zzi000$onRenderTileEntities(WorldRenderer:4716)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1265)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
Details:
	Name: minecraft:ender_chest // net.minecraft.class_2611
	Block: Block{minecraft:ender_chest}[facing=east,waterlogged=false]
	Block location: World: (1343,126,352), Chunk: (at 15,7,0 in 83,22; contains blocks 1328,0,352 to 1343,255,367), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Block: Block{minecraft:ender_chest}[facing=east,waterlogged=false]
	Block location: World: (1343,126,352), Chunk: (at 15,7,0 in 83,22; contains blocks 1328,0,352 to 1343,255,367), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Block Entity NBT: {x:1343,y:126,z:352,id:"minecraft:ender_chest"}
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:131)
	at net.minecraft.class_824.method_3555(class_824.java:96)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:325)
	at net.minecraft.class_761.handler$zzi000$onRenderTileEntities(class_761.java:4716)
	at net.minecraft.class_761.method_22710(class_761.java:1265)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- Affected level --
Details:
	All players: 1 total; [class_746['_K0RR_'/116, l='ClientLevel', x=1284.07, y=135.98, z=335.09]]
	Chunk stats: SodiumChunkCache: 3425
	Level dimension: minecraft:the_end
	Level spawn location: World: (-208,63,49), Chunk: (at 0,3,1 in -13,3; contains blocks -208,0,48 to -193,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 96746 game time, 96746 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-50-generic
	Java Version: 11.0.11, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 1405546128 bytes (1340 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	Suspected Mods: Enhanced Block Entities (enhancedblockentities), Fabric Loader (fabricloader), Sodium (sodium)
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.12
		alloy_forgery: Alloy Forgery 1.1.0
		amecs: Amecs 1.3.4+mc.1.16.3
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.12.145
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		automatone: Automatone 0.3.3
		bambootweaks: Bamboo Tweaks 2.0.5
		banner_capes: Banner Capes 0.2.1
		battletowers: Battle Towers 3.3.4-1.16.4
		bedrockify: BedrockIfy 1.1.0+mc1.16.2-5
		bendy-lib: Bendy api 1.1.0
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.6-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blame: Blame 1.16.4-2.4.1
		bundlesplus: bundles plus 0.1.8
		byg: BYG 1.1.7
		campanion: Campanion 1.3.5
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
		carpet: Carpet Mod 1.4.35
		carpet-extra: Carpet Extra 1.4.34
		carpet-tis-addition: Carpet TIS Addition 1.18.0
		cavebiomes: Cave Biomes 0.6.2
		charm: Charm 2.3.3-snapshot
		chesttracker: Chest Tracker 0.8.13
		chunky: Chunky 1.2.54
		cinderscapes: Cinderscapes 1.3.3
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		consistency_plus: Consistency Plus 0.3.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		croptopia: Croptopia 1.3.5
		cullleaves: Cull Leaves 2.1.0
		customportals: Custom Portals 1.4.2
		darkness: True Darkness 1.6.58
		defaultsettings: DefaultSettings 3.0.2
		dehydration: Dehydration 1.1.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		emotecraft: Emotecraft 2.0.3
		enchant_giver: Enchant Giver 1.0.3
		enhancedblockentities: Enhanced Block Entities 0.3
		entityculling: EntityCulling-Fabric 1.2.2
		environmentz: EnvironmentZ 1.0.13
		extrasounds: Extra Sounds 1.0.0
		fabric: Fabric API 0.34.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabrication: Fabrication 1.3.4
		fabricloader: Fabric Loader 0.11.3
		fabrilousupdater: FabrilousUpdater 1.0.5
		fading: Fading 1.2.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		firstperson: FirstpersonModel 2.0.1
		fluidphysics: Fluid Physics 1.4.0+fabric-1.16.4
		full_slabs: Full Slabs 2.0.1
		geckolib3: Geckolib 3.0.30
		impersonate: Impersonate 2.2.0
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 11
		kibe: Kibe 1.6.7-BETA
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		lengthyladders: Lengthy Ladders 1.0.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libgui: LibGui 3.3.5+1.16.5
		libstructure: LibStructure 1.5
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4-SNAPSHOT
		loading-timer: Loading Timer 1.4.2-Snapshot
		make-every-biome-spawnable-lol: Make Every Biome Spawnable 1.16.5-1.1.0
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		map_atlases: Map Atlases 1.2.5
		micalibria: Micalibria 1.0.2
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		modifiers: Modifiers 0.1.1
		modmenu: Mod Menu 1.16.9
		more_gems: More Gems 1.1.22
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mythicmetals: Mythic Metals 0.9.9
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		noplayerlabels: No Player Labels 2.0.1
		notenoughanimations: NotEnoughAnimations 1.2.4
		notenoughcrashes: Not Enough Crashes 3.2.0
		oldregen: Good Ol' Regen 1.0.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
		origins: Origins 0.7.0
		pandemonium: Requiem: Pandemonium 1.6.3
		pandemoniumapi: Requiem: Pandemonium-API 1.6.3
		playerabilitylib: Pal 1.2.1
		pride: Pride Lib 1.0.0+1.16
		puddles: Puddles 1.0.0
		randompatches: RandomPatches 2.4.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		requiem: Requiem 1.6.3
		requiemapi: Requiem-API 1.6.3
		retail: Retail 0.2.0
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		satin: Satin 1.5.1
		seamless_loading_screen: Seamless Loading Screen 1.3.4
		sentimentality2: Sentimentality 2 1.1.0
		sextant: Immersive Travel Overhaul 0.3
		sodium: Sodium 0.1.1+build.330
		spark: spark 1.5.2
		spruceui: SpruceUI 2.0.4+1.16
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.2.1
		structure-helpers: Structure Helpers 3.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.1
		throwabletorch: ThrowableTorch 1.16.5
		timecraft: Craft Takes Time 0.4.4
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		transliterationlib: TRansliterationLib 1.0.4
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20210204.204245
		unearthed: Unearthed 1.1.1
		voyager: Voyager 1.0.0
		waystones: Waystones 1.1.1.1
		whereisit: Where Is It 1.11.7
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.73.01, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, cullleaves/smartleaves
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
```

**Comment by FoundationGames** [comment]
Fixed in 0.3.1
